In [2]:
import pandas as pd
import numpy as np

/Users/sarvinshahir/opt/anaconda3/lib/python3.8/site-packages/pandas/core/computation/expressions.py:20: UserWarning: Pandas requires version '2.7.3' or newer of 'numexpr' (version '2.7.1' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED

In [4]:
df = pd.read_csv('Impact_of_Remote_Work_on_Mental_Health.csv')
df.head()

,Employee_ID,Age,Gender,Job_Role,Industry,Years_of_Experience,Work_Location,Hours_Worked_Per_Week,Number_of_Virtual_Meetings,Work_Life_Balance_Rating,Stress_Level,Mental_Health_Condition,Access_to_Mental_Health_Resources,Productivity_Change,Social_Isolation_Rating,Satisfaction_with_Remote_Work,Company_Support_for_Remote_Work,Physical_Activity,Sleep_Quality,Region
0,EMP0001,32,Non-binary,HR,Healthcare,13,Hybrid,47,7,2,Medium,Depression,No,Decrease,1,Unsatisfied,1,Weekly,Good,Europe
1,EMP0002,40,Female,Data Scientist,IT,3,Remote,52,4,1,Medium,Anxiety,No,Increase,3,Satisfied,2,Weekly,Good,Asia
2,EMP0003,59,Non-binary,Software Engineer,Education,22,Hybrid,46,11,5,Medium,Anxiety,No,No Change,4,Unsatisfied,5,NaN,Poor,North America
3,EMP0004,27,Male,Software Engineer,Finance,20,Onsite,32,8,4,High,Depression,Yes,Increase,3,Unsatisfied,3,NaN,Poor,Europe
4,EMP0005,49,Male,Sales,Consulting,32,Onsite,35,12,2,High,NaN,Yes,Decrease,3,Unsatisfied,3,Weekly,Average,North America

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 20 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Employee_ID                        5000 non-null   object
 1   Age                                5000 non-null   int64
 2   Gender                             5000 non-null   object
 3   Job_Role                           5000 non-null   object
 4   Industry                           5000 non-null   object
 5   Years_of_Experience                5000 non-null   int64
 6   Work_Location                      5000 non-null   object
 7   Hours_Worked_Per_Week              5000 non-null   int64
 8   Number_of_Virtual_Meetings         5000 non-null   int64
 9   Work_Life_Balance_Rating           5000 non-null   int64
 10  Stress_Level                       5000 non-null   object
 11  Mental_Health_Condition            3804 non-null   object
 12  Access_to_Mental_Health_Resources  5000 non-null   object
 13  Productivity_Change                5000 non-null   object
 14  Social_Isolation_Rating            5000 non-null   int64
 15  Satisfaction_with_Remote_Work      5000 non-null   object
 16  Company_Support_for_Remote_Work    5000 non-null   int64
 17  Physical_Activity                  3371 non-null   object
 18  Sleep_Quality                      5000 non-null   object
 19  Region                             5000 non-null   object
dtypes: int64(7), object(13)
memory usage: 781.4+ KB

In [8]:
categorical_columns = df.select_dtypes(include=['object']).columns

for column in categorical_columns:
    print(f"Categories in '{column}':")
    print(df[column].unique(), "\n")

Categories in 'Employee_ID':
['EMP0001' 'EMP0002' 'EMP0003' ... 'EMP4998' 'EMP4999' 'EMP5000']

Categories in 'Gender':
['Non-binary' 'Female' 'Male' 'Prefer not to say']

Categories in 'Job_Role':
['HR' 'Data Scientist' 'Software Engineer' 'Sales' 'Marketing' 'Designer'
 'Project Manager']

Categories in 'Industry':
['Healthcare' 'IT' 'Education' 'Finance' 'Consulting' 'Manufacturing'
 'Retail']

Categories in 'Work_Location':
['Hybrid' 'Remote' 'Onsite']

Categories in 'Stress_Level':
['Medium' 'High' 'Low']

Categories in 'Mental_Health_Condition':
['Depression' 'Anxiety' nan 'Burnout']

Categories in 'Access_to_Mental_Health_Resources':
['No' 'Yes']

Categories in 'Productivity_Change':
['Decrease' 'Increase' 'No Change']

Categories in 'Satisfaction_with_Remote_Work':
['Unsatisfied' 'Satisfied' 'Neutral']

Categories in 'Physical_Activity':
['Weekly' nan 'Daily']

Categories in 'Sleep_Quality':
['Good' 'Poor' 'Average']

Categories in 'Region':
['Europe' 'Asia' 'North America' 'South America' 'Oceania' 'Africa']

In [9]:
df_cleaned = df.dropna()
df_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2577 entries, 0 to 4997
Data columns (total 20 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Employee_ID                        2577 non-null   object
 1   Age                                2577 non-null   int64
 2   Gender                             2577 non-null   object
 3   Job_Role                           2577 non-null   object
 4   Industry                           2577 non-null   object
 5   Years_of_Experience                2577 non-null   int64
 6   Work_Location                      2577 non-null   object
 7   Hours_Worked_Per_Week              2577 non-null   int64
 8   Number_of_Virtual_Meetings         2577 non-null   int64
 9   Work_Life_Balance_Rating           2577 non-null   int64
 10  Stress_Level                       2577 non-null   object
 11  Mental_Health_Condition            2577 non-null   object
 12  Access_to_Mental_Health_Resources  2577 non-null   object
 13  Productivity_Change                2577 non-null   object
 14  Social_Isolation_Rating            2577 non-null   int64
 15  Satisfaction_with_Remote_Work      2577 non-null   object
 16  Company_Support_for_Remote_Work    2577 non-null   int64
 17  Physical_Activity                  2577 non-null   object
 18  Sleep_Quality                      2577 non-null   object
 19  Region                             2577 non-null   object
dtypes: int64(7), object(13)
memory usage: 422.8+ KB

In [10]:
categorical_columns = df_cleaned.select_dtypes(include=['object']).columns

for column in categorical_columns:
    print(f"Categories in '{column}':")
    print(df_cleaned[column].unique(), "\n")

Categories in 'Employee_ID':
['EMP0001' 'EMP0002' 'EMP0007' ... 'EMP4995' 'EMP4996' 'EMP4998']

Categories in 'Gender':
['Non-binary' 'Female' 'Prefer not to say' 'Male']

Categories in 'Job_Role':
['HR' 'Data Scientist' 'Sales' 'Marketing' 'Designer' 'Project Manager'
 'Software Engineer']

Categories in 'Industry':
['Healthcare' 'IT' 'Consulting' 'Manufacturing' 'Retail' 'Education'
 'Finance']

Categories in 'Work_Location':
['Hybrid' 'Remote' 'Onsite']

Categories in 'Stress_Level':
['Medium' 'Low' 'High']

Categories in 'Mental_Health_Condition':
['Depression' 'Anxiety' 'Burnout']

Categories in 'Access_to_Mental_Health_Resources':
['No' 'Yes']

Categories in 'Productivity_Change':
['Decrease' 'Increase' 'No Change']

Categories in 'Satisfaction_with_Remote_Work':
['Unsatisfied' 'Satisfied' 'Neutral']

Categories in 'Physical_Activity':
['Weekly' 'Daily']

Categories in 'Sleep_Quality':
['Good' 'Poor' 'Average']

Categories in 'Region':
['Europe' 'Asia' 'North America' 'Oceania' 'Africa' 'South America']

In [12]:
data_filtered = df_cleaned[df_cleaned['Gender'] != 'Prefer not to say']
data_filtered.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1947 entries, 0 to 4997
Data columns (total 20 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Employee_ID                        1947 non-null   object
 1   Age                                1947 non-null   int64
 2   Gender                             1947 non-null   object
 3   Job_Role                           1947 non-null   object
 4   Industry                           1947 non-null   object
 5   Years_of_Experience                1947 non-null   int64
 6   Work_Location                      1947 non-null   object
 7   Hours_Worked_Per_Week              1947 non-null   int64
 8   Number_of_Virtual_Meetings         1947 non-null   int64
 9   Work_Life_Balance_Rating           1947 non-null   int64
 10  Stress_Level                       1947 non-null   object
 11  Mental_Health_Condition            1947 non-null   object
 12  Access_to_Mental_Health_Resources  1947 non-null   object
 13  Productivity_Change                1947 non-null   object
 14  Social_Isolation_Rating            1947 non-null   int64
 15  Satisfaction_with_Remote_Work      1947 non-null   object
 16  Company_Support_for_Remote_Work    1947 non-null   int64
 17  Physical_Activity                  1947 non-null   object
 18  Sleep_Quality                      1947 non-null   object
 19  Region                             1947 non-null   object
dtypes: int64(7), object(13)
memory usage: 319.4+ KB

In [13]:
categorical_columns = data_filtered.select_dtypes(include=['object']).columns

for column in categorical_columns:
    print(f"Categories in '{column}':")
    print(data_filtered[column].unique(), "\n")

Categories in 'Employee_ID':
['EMP0001' 'EMP0002' 'EMP0010' ... 'EMP4992' 'EMP4996' 'EMP4998']

Categories in 'Gender':
['Non-binary' 'Female' 'Male']

Categories in 'Job_Role':
['HR' 'Data Scientist' 'Marketing' 'Designer' 'Sales' 'Software Engineer'
 'Project Manager']

Categories in 'Industry':
['Healthcare' 'IT' 'Consulting' 'Manufacturing' 'Retail' 'Education'
 'Finance']

Categories in 'Work_Location':
['Hybrid' 'Remote' 'Onsite']

Categories in 'Stress_Level':
['Medium' 'Low' 'High']

Categories in 'Mental_Health_Condition':
['Depression' 'Anxiety' 'Burnout']

Categories in 'Access_to_Mental_Health_Resources':
['No' 'Yes']

Categories in 'Productivity_Change':
['Decrease' 'Increase' 'No Change']

Categories in 'Satisfaction_with_Remote_Work':
['Unsatisfied' 'Satisfied' 'Neutral']

Categories in 'Physical_Activity':
['Weekly' 'Daily']

Categories in 'Sleep_Quality':
['Good' 'Poor' 'Average']

Categories in 'Region':
['Europe' 'Asia' 'North America' 'Africa' 'Oceania' 'South America']

In [14]:
data_filtered.to_csv('new_df.csv')